name: Compile And Unit Test
on:
  push:
    branches: [ "*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 配置maven
        uses: actions/setup-java@v4.2.1
        with: 
          java-version: '8'
          distribution: 'adopt'
          java-package: 'jdk'
      - name: Compile Project
        run: |
          mvn clean compile
      - name: verify Project
        run: |
          mvn verify
